apiVersion: v1
kind: Service
metadata:
  name: weather-app-service
  namespace: default
spec:
  selector:
    app: weather-app
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
  type: ClusterIP
