name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-and-deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Build and push Docker image
      run: |
        # Define the version tag
        VERSION_TAG=v2.0.2  # Replace with your version
        docker build . --file Dockerfile --tag alkimik/weather-app:${VERSION_TAG}
        docker push alkimik/weather-app:${VERSION_TAG}

    - name: Update Kubernetes Deployment
      run: |
        kubectl set image deployment/weather-app weather-app=alkimik/weather-app:${VERSION_TAG} --namespace=default
